### ISSUE TITLE
内存泄漏问题

### ISSUE THREAD

**Issue by LegionFu** [Beginner258/Kinect_Cursor_Control#7]
大兄弟 你的代码有内存泄漏啊。。。我跑一个小时，内存占用就有几百兆了。。

**Comment by LegionFu** [comment]
找到原因了，在While(1)循环的后面 加上：
for (int i = 0; i < bodyBufferSize; i++)
			bodyArray[i]->Release();

**Comment by air798** [comment]
> 找到原因了，在While(1)循环的后面 加上：
> for (int i = 0; i < bodyBufferSize; i++)
> bodyArray[i]->Release();

大佬，我想买你的视频插件.....
